# Generated by Django 4.1.5 on 2023-02-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('pswd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
    ]
